### ISSUE TITLE
Model methy influence on change in max transcript

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#96]

**Comment by sr320** [comment]
Believe files at https://github.com/sr320/ceabigr/tree/main/output/73-gene-methylation

will be helpful.

**Comment by sr320** [comment]
going to say does not influence... https://htmlpreview.github.io/?https://github.com/sr320/ceabigr/blob/main/code/76-meth-maxtranscript.html

**Comment by yaaminiv** [comment]
@kubu4 @sr320 where can I find a data frame that also includes genes where there wasn't a change in the max transcript expressed? I need that to do a statistical test

**Comment by kubu4** [comment]
This file will have it, but you'll have to filter on your own:

`supplemental-files/01.01-fmcoe-max-predom-isos-gene_fpkm.csv`

```r
'data.frame':	39014 obs. of  18 variables:
 $ gene_name                             : chr  "ATP6" "COX1" "COX2" "COX3" ...
 $ females_controls_max_transcript_counts: int  1 1 1 1 1 1 1 1 1 1 ...
 $ males_controls_max_transcript_counts  : int  1 1 1 1 1 1 1 1 1 1 ...
 $ females_exposed_max_transcript_counts : int  1 1 1 1 1 1 1 0 1 1 ...
 $ males_exposed_max_transcript_counts   : int  1 1 1 1 1 1 1 1 1 1 ...
 $ max_transcript_counts                 : int  1 1 1 1 1 1 1 1 1 1 ...
 $ females_controls_predom_isoform       : chr  "gene-ATP6" "gene-COX1" "gene-COX2" "gene-COX3" ...
 $ females_exposed_predom_isoform        : chr  "gene-ATP6" "gene-COX1" "gene-COX2" "gene-COX3" ...
 $ males_controls_predom_isoform         : chr  "gene-ATP6" "gene-COX1" "gene-COX2" "gene-COX3" ...
 $ males_exposed_predom_isoform          : chr  "gene-ATP6" "gene-COX1" "gene-COX2" "gene-COX3" ...
 $ females_controls_predom_expression    : num  1557 2621 3303 1337 3732 ...
 $ females_exposed_predom_expression     : num  1624 2420 3077 1281 3929 ...
 $ males_controls_predom_expression      : num  98.7 159.5 177.2 154.1 218.5 ...
 $ males_exposed_predom_expression       : num  201 538 674 399 837 ...
 $ females_controls_mean_gene_FPKM       : num  1488 2581 3332 1277 3606 ...
 $ females_exposed_mean_gene_FPKM        : num  1631 2463 3219 1333 3944 ...
 $ males_controls_mean_gene_FPKM         : num  174 360 427 319 510 ...
 $ males_exposed_mean_gene_FPKM          : num  164 413 499 316 615 ...
```

**Comment by sr320** [comment]
here is how I filtered .... https://github.com/sr320/ceabigr/blob/6e6295665fab8be1465bbd6b25258fb158a7cf03/code/76-meth-maxtranscript.qmd#L93

see https://htmlpreview.github.io/?https://github.com/sr320/ceabigr/blob/main/code/76-meth-maxtranscript.html

**Comment by yaaminiv** [comment]
Modeled in two ways:  1) the difference in maximum transcripts expressed or 2) whether or not there was a change in the maximum number of transcripts.

Females:

- standard model output: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/fem-max-trans-model-output.csv
- binomial model output: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/fem-max-trans-binomial-model-output.csv

Males:

- standard model output: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/male-max-trans-model-output.csv
- binomial model output: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/male-max-trans-binomial-model-output.csv

I'll include the binomial model output in the main text since that's probably more conservative/we have more stat power for that and the methods are similar to the predominant isoform model
